### PR TITLE
Validate Composer config

### PR DESCRIPTION
**Pull request by szepeviktor**

### CODE REVIEW

**Comment by szepeviktor** [comment]
It was expected to fail :)

kép

@paulthewalton What do you think?

**Comment by szepeviktor** [comment]
Suggestions

1. simply update license name
1. remove `version` field
1. `"php-stubs/woocommerce-stubs": "^4.7 || ^5.0",` see https://github.com/AdvancedCustomFields/acf/blob/master/readme.txt#L4

**Comment by paulthewalton** [comment]
@szepeviktor 

1. agree
2. agree, & one less thing to remember for updates
3. is there a reason you suggested `woocommerce-stubs` instead of `wordpress-stubs`, or is that unintentional?

**Comment by szepeviktor** [comment]
I'm sorry.
`woocommerce-stubs` is a TYPO!

**Pull request merged**
